# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 9f43b166-f676-4c12-9c16-639a6140c85b-capi-aws-check
  namespace: 9f43b166-f676-4c12-9c16-639a6140c85b
spec:
  template:
    metadata:
      name: 9f43b166-f676-4c12-9c16-639a6140c85b-capi-aws
    spec:
      serviceAccountName: 9f43b166-f676-4c12-9c16-639a6140c85b-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 9f43b166-f676-4c12-9c16-639a6140c85b
        - 9f43b166-f676-4c12-9c16-639a6140c85b
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 9f43b166-f676-4c12-9c16-639a6140c85b-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
